import { Inter, Poppins } from "next/font/google";
import "./globals.scss";
import Navbar from "@/components/home/header/Navbar";
import Footer from "@/components/home/footer/Footer";
import FooterCta from "@/components/home/footer/FooterCta";
import AOSInitiator from "@/lib/aos-initiator";
import { Toaster } from "@/components/ui/toaster"

const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({ subsets: ["latin"], weight: ['400', '500', '600', '700'] })

export const metadata = {
  title: "Quiva AI",
  description: "Generated by create next app",
  icons: {
    icon: "./favicon.ico"
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} bg-[#051119]`} >
        <AOSInitiator>
          <div className="absolute inset-0 w-full h-full bg-gradient-to-b from-slate-900/0 to-transparent z-20 [mask-image:radial-gradient(transparent,white)] pointer-events-none" />
          <Navbar />

          <div className="bg-[#08121D]">
            {children}
          </div>
          <FooterCta />
          <Footer />
          <Toaster />
        </AOSInitiator>

      </body>
    </html>
  );
}
